// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_backup.Data;

#nullable disable

namespace web_backup.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260812191739_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AmenityRoom", b =>
                {
                    b.Property<int>("AmenitiesId")
                        .HasColumnType("int");

                    b.Property<int>("RoomsId")
                        .HasColumnType("int");

                    b.HasKey("AmenitiesId", "RoomsId");

                    b.HasIndex("RoomsId");

                    b.ToTable("AmenityRoom");
                });

            modelBuilder.Entity("web_backup.Models.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("web_backup.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Phòng trọ"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chung cư mini"
                        });
                });

            modelBuilder.Entity("web_backup.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("HasMezzanine")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Chính chủ | Gác lửng",
                            Area = 16.600000000000001,
                            CategoryId = 1,
                            HasMezzanine = true,
                            ImageUrl = "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
                            IsOwner = true,
                            Price = 180000m,
                            Title = "Phòng trọ Q1 full nội thất"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Chính chủ | Gác lửng",
                            Area = 15.5,
                            CategoryId = 2,
                            HasMezzanine = true,
                            ImageUrl = "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
                            IsOwner = true,
                            Price = 180000m,
                            Title = "Chung cư mini Bình Thạnh"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Chính chủ | Gác lửng",
                            Area = 31.0,
                            CategoryId = 2,
                            HasMezzanine = true,
                            ImageUrl = "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
                            IsOwner = true,
                            Price = 128000m,
                            Title = "Chung cư mini Bình Thạnh"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Hồ Chí Minh Bình Thạnh",
                            Area = 3.3500000000000001,
                            CategoryId = 1,
                            HasMezzanine = true,
                            ImageUrl = "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
                            IsOwner = true,
                            Price = 180000m,
                            Title = "Phòng trọ Q1 full nội thất"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Hồ Chí Minh Bình Thạnh",
                            Area = 375.0,
                            CategoryId = 1,
                            HasMezzanine = true,
                            ImageUrl = "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd",
                            IsOwner = true,
                            Price = 179000m,
                            Title = "Phòng trọ Q1 full nội thất"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Hồ Chí Minh Bình Thạnh",
                            Area = 26.949999999999999,
                            CategoryId = 2,
                            HasMezzanine = true,
                            ImageUrl = "https://images.unsplash.com/photo-1484154218962-a197022b5858",
                            IsOwner = true,
                            Price = 168000m,
                            Title = "Chung cư mini Bình Thạnh"
                        });
                });

            modelBuilder.Entity("AmenityRoom", b =>
                {
                    b.HasOne("web_backup.Models.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web_backup.Models.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("web_backup.Models.Room", b =>
                {
                    b.HasOne("web_backup.Models.Category", "Category")
                        .WithMany("Rooms")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("web_backup.Models.Category", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
